artifact:
	dependencies:	( intro, content, outro )

intro:
	dependencies:	( dependency4, dependency5 )

content:
	dependencies:	( dependency6, dependency7 )

outro:
	dependencies:	( dependency8, dependency9 )
