artifact:
	dependencies:	( a )
	steps:	( echo build artifact -d a ,b ,c )

a:
	dependencies:	( b )
	steps:	( echo build artifact -d e )

b:
	dependencies:	( c )
	steps:	( echo build artifact -d f )

c:
	dependencies:	( d )
	steps:	( echo build artifact -d f )

d:
	dependencies:	( g )
	steps:	( echo build artifact -d g )

